"""Atomic JSON artifact publication."""

import json
import os
from pathlib import Path
import tempfile

from pydantic import BaseModel

from workflow_container_runtime.model import model_snapshot_get


def shared_artifact_directory_prepare(path: Path) -> None:
    """Prepare one declared directory for cooperating container processes.

    Args:
        path: Exact external artifact write directory.
    """

    path.mkdir(parents=True, exist_ok=True)
    path.chmod(0o777)


class JsonArtifactWriter:
    """Publish deterministic JSON artifacts durably."""

    def schema_write(self, path: Path, model: type[BaseModel]) -> None:
        """Publish a strict structured-output schema generated by one exact model.

        Args:
            path: Schema artifact path.
            model: Pydantic model that owns the schema.
        """

        schema = model.model_json_schema()
        self._schema_strict_normalize(schema)
        self._json_write(path=path, value=schema)

    def write(self, path: Path, value: BaseModel) -> None:
        """Publish one validated model as canonical JSON.

        Args:
            path: Artifact path to write.
            value: Validated Pydantic model.
        """

        snapshot = model_snapshot_get(value)
        self._json_write(path=path, value=snapshot.model_dump(mode="json"))

    def _directory_sync(self, path: Path) -> None:
        """Synchronize one directory entry set.

        Args:
            path: Directory path to synchronize.
        """

        directory_descriptor = os.open(path, os.O_RDONLY)
        try:
            os.fsync(directory_descriptor)
        finally:
            os.close(directory_descriptor)

    def _json_write(self, *, path: Path, value: object) -> None:
        """Atomically publish one JSON-compatible value.

        Args:
            path: Artifact path to publish.
            value: JSON-compatible value.
        """

        path.parent.mkdir(parents=True, exist_ok=True)
        payload = json.dumps(value, indent=2, sort_keys=True) + "\n"
        temporary_path: Path | None = None
        try:
            with tempfile.NamedTemporaryFile(
                dir=path.parent,
                encoding="utf-8",
                mode="w",
                prefix=f".{path.name}.",
                delete=False,
            ) as temporary_file:
                temporary_path = Path(temporary_file.name)
                temporary_file.write(payload)
                temporary_file.flush()
                os.fsync(temporary_file.fileno())
            os.replace(temporary_path, path)
            temporary_path = None
            self._directory_sync(path.parent)
        finally:
            if temporary_path is not None and temporary_path.exists():
                temporary_path.unlink()

    def _schema_strict_normalize(self, schema: object) -> None:
        """Require every declared object property in a structured-output schema.

        Args:
            schema: JSON Schema node to normalize in place.
        """

        if isinstance(schema, dict):
            property_by_name_map = schema.get("properties")
            if isinstance(property_by_name_map, dict):
                schema["additionalProperties"] = False
                schema["required"] = sorted(property_by_name_map)
            for value in schema.values():
                self._schema_strict_normalize(value)
            return
        if isinstance(schema, list):
            for value in schema:
                self._schema_strict_normalize(value)
